Update cache-clear.sh
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ecommerceframework_productindex' doesn't exist https://github.com/pimcore/pimcore/discussions/14258